##
##  Makefile -- Build procedure for sample mod_myson Apache module
##  Autogenerated via ``apxs -n mod_myson -g''.
##

builddir=.
top_srcdir=/usr
top_builddir=/usr
# include /usr/share/httpd/build/special.mk

#   the used tools
APXS=sudo apxs
APACHECTL=sudo apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I/usr/local/mysql/include
LIBS=-L/usr/local/mysql/lib -lmysqlclient

#   the default target
all:
	$(APXS) $(INCLUDES) $(LIBS) -a -c -i mod_myson.c apr_json_decode.c apr_json_encode.c
	$(APACHECTL) restart

#   install the shared object file into Apache 
install:
	sudo $(APXS) -i mod_myson.c

#   cleanup
clean:
	-rm -f mod_mod_myson.o mod_mod_myson.lo mod_mod_myson.slo mod_mod_myson.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mod_myson

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

